kind: Service
apiVersion: v1
metadata:
  name: helidon 
  labels:
    app: helidon 
spec:
  type: NodePort
  selector:
    app: helidon 
  ports:
  - port: 8080 
    targetPort: 8080    
    nodePort: 30007

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: helidon
  labels:
    app: helidon
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helidon
  template:
    metadata:
      labels:
        app: helidon
    spec:
      containers:
      - name: helidon
        image: tmontovaneli/helidon
        ports:
        - containerPort: 8080
---